### ISSUE TITLE
Feature request: easy way to deactivate or simulate sending 

### ISSUE THREAD

**Issue by mnellemann** [mathifonseca/grails-slack#10]
Hi,
When running Grails in development or test, it would be helpful if there was a config option that would disable the integration or do a 'dry run' simulation.

Br,

**Comment by mathifonseca** [comment]
Hi @mnellemann, I've just published a new version for both Grails versions. Can you try it and let me know?
Grails 2.x -> 1.3.0
Grails 3.x -> 3.2.0
