### ISSUE TITLE
Will be supported Grails 3.x?

### ISSUE THREAD

**Issue by magx2** [mathifonseca/grails-slack#2]
I'm just wondering if this plugin support Grails 3? I must say that I'm pretty interested in this feature.

**Comment by mathifonseca** [comment]
I haven't migrated it yet :( I'll do it this weekend if that's ok for you, is it?

**Comment by magx2** [comment]
OK, it would be great!

**Comment by magx2** [comment]
Any update?

**Comment by mathifonseca** [comment]
Hi @magx2, have you tried the new version?

**Comment by magx2** [comment]
Hi, thanks for posting here! I didn't get notifications about PR #3 so I didn't know that anything changed.

Will try it in a moment.

One more time thanks!
