### ISSUE TITLE
Allow channel ids instead of names

### ISSUE THREAD

**Issue by entropitor** [mathifonseca/grails-slack#7]
Allow channel ids to be used.

https://github.com/mathifonseca/grails-slack/blob/54d70fbd4c9dede2bd6561c924b45837761cabfd/src/main/groovy/grails/plugin/slack/SlackMessage.groovy#L26

it should not always start with `#` or `@`; `U` (user), `C` (public channel) and `G` (private channel) are also allowed (maybe even more, I think it's best to remove the check). 

See section "channel override" on https://api.slack.com/incoming-webhooks:

> If you prefer, you can also specify a channel ID or user ID like so: "channel": "U024BE7LH".

**Comment by mathifonseca** [comment]
Hi @caske33! Thanks for noticing that. I've just removed the regex and simply added a check for it not to be blank. Please check version 3.1.1 (grails 3.x) or 1.2.1 (grails 2.x) and let me know if it's ok for you.
