### ISSUE TITLE
When tried to send message from grails app 2nd time, got exception.

### ISSUE THREAD

**Issue by anythingrandom** [mathifonseca/grails-slack#8]
In the first time it posted the message correctly to slack channel, but when tried to send 2nd time it gave exception.
org.apache.commons.lang.UnhandledException:
org.codehaus.groovy.grails.web.converters.exceptions.ConverterException:
at grails.plugin.slack.SlackService.send(SlackService.groovy:27)

**Comment by mathifonseca** [comment]
Hi, can you tell me your Grails version? And can you paste the complete stacktrace and an example of message you are trying to send?

**Comment by anythingrandom** [comment]
grails version 2.3.8
message i am trying to send:
I have a domain class named Sleep.
String message = 'Slept at: '+sleep.sleptAt  + '\n' + "Woke at: "+sleep.wokeUpAt + '\n' + 'You slept for ' + sleep.getDuration()
slackService.send {
				text message
				username 'Sleep Tracker'	
			}
Details of Exception:
Class: java.lang.IllegalAccessException
Message
Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public"
Around line 27 of grails-app/services/grails/plugin/slack/SlackService.groovy
24:			throw new SlackMessageException("Slack webhook is not valid")
25:		}
26:
27:    	String jsonMessage = message.encodeAsJson().toString()
28:
29:    	log.debug "Sending message : ${jsonMessage}"
30:

Full stacktrace:
Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public". Stacktrace follows:
Message: Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public"
    Line | Method
->>  201 | value          in grails.converters.JSON
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    161 | convertAnother in     ''
|    201 | value . . . .  in     ''
|    161 | convertAnother in     ''
|    201 | value . . . .  in     ''
|    161 | convertAnother in     ''
|    201 | value . . . .  in     ''
|    161 | convertAnother in     ''
|    201 | value . . . .  in     ''
|    133 | render         in     ''
|     27 | send . . . . . in grails.plugin.slack.SlackService
|     55 | create         in com.x.y.z
|    198 | doFilter . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter       in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run            in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . .  in java.lang.Thread

**Comment by anythingrandom** [comment]
It seems something related to this 
http://grails.1312388.n4.nabble.com/Marshallers-are-blowing-up-in-2-3-5-anyone-else-td4653954.html

**Comment by lesiki** [comment]
@anythingrandom did you find a way around this? Facing the same issue in my Grails 2.4.3 app.

**Comment by mathifonseca** [comment]
@anythingrandom @lesiki Hi! I can't reproduce what you're getting. Seems to have something to do with some strange combination of dependencies, or if you are doing some magic with Marshallers. Can you give me some more info?

**Comment by lesiki** [comment]
Hey, yeah I wouldn't rule this out of being some dependency clash. I'm not doing any custom marshalling at all though.

My stacktrace:

```
Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public". Stacktrace follows:
java.lang.IllegalAccessException: Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public"
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.convertAnother(JSON.java:162)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.convertAnother(JSON.java:162)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.convertAnother(JSON.java:162)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.convertAnother(JSON.java:162)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.render(JSON.java:134)
	at grails.plugin.slack.SlackService.send(SlackService.groovy:27)
```

**Comment by mathifonseca** [comment]
@lesiki hi! what I usually do to find these kinds of dependency problems is to create a new Grails app and start adding the plugins one by one to see when and which is the one that breaks everything. For trying to reproduce your bug for example, I created a blank Grails 2.4.3 application and only added the Slack plugin. It all worked fine. If you have the time, could you do that so that we discover where the problem is?

**Comment by lesiki** [comment]
Sure @mathifonseca I'll do some digging. Closest I found was [this discussion](http://grails.1312388.n4.nabble.com/Removing-class-attributes-from-JSON-responses-td4630631.html) that suggested the error comes from the marshaller trying to handle the 'errors' property, but from a look at the code it looks like your custom marshaller handles it.

It might be custom marshalling 'collision' from something in my plugins, so I'll incrementally add them and see what happens.

**Comment by lesiki** [comment]
I've been able to reproduce this in a new Grails 2.4.3 app, with only one controller that calls slackService.send in it's index method. This is using version 1.2.1, and no other dependencies (other than those added by `grails create-app`)

I tried with both java 7 and 8, and got the same behaviour - first call works as expected, second one results in this error

```
Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public". Stacktrace follows:
Message: Class org.codehaus.groovy.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public"
    Line | Method
->>  202 | value          in grails.converters.JSON
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    162 | convertAnother in     ''
|    202 | value . . . .  in     ''
|    162 | convertAnother in     ''
|    202 | value . . . .  in     ''
|    162 | convertAnother in     ''
|    202 | value . . . .  in     ''
|    162 | convertAnother in     ''
|    202 | value . . . .  in     ''
|    134 | render         in     ''
|     27 | send . . . . . in grails.plugin.slack.SlackService
|      7 | index          in slackbug.TheOnlyController
|    198 | doFilter . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter       in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run            in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . .  in java.lang.Thread
```

**Comment by mathifonseca** [comment]
Hi @lesiki @anythingrandom! I found the problem! It was because some strange behaviour caused after setting a custom marshaller for the objects sent to Slack. Please upgrade to version `1.2.2` and let me know if it works.

**Comment by lesiki** [comment]
Works perfect after the upgrade. Dropping the converters was going to be the first thing I tried, was hoping I'd sneak in a contribution but you beat me to it 😉.

Thanks for the quick fix!

**Comment by mathifonseca** [comment]
Actually, removing the custom converters is not the best option. I did it
like that because I don't have much time right now. With this solution,
some of Grails' "magic" fields will get converted to JSON and sent to
Slack. That's why the converters were there before. It works fine anyway
because Slack API ignores them, but it would be nice to clean our request
so that only the necessary data travels to Slack. So there's your chance to
contribute :)

On 25 Jan 2017 17:52, "lesiki" <notifications@github.com> wrote:

Works perfect after the upgrade. Dropping the converters was going to be
the first thing I tried, was hoping I'd sneak in a contribution but you
beat me to it 😉.

Thanks for the quick fix!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mathifonseca/grails-slack/issues/8#issuecomment-275229420>,
or mute the thread

**Comment by anythingrandom** [comment]
Hi @mathifonseca Thanks for you upgrade! Sorry for my absence for long. I will try the upgrade soon.
By the way in the mean time i was using the grails plugin which sends logs to slack to fulfill my need.

**Comment by t2developer** [comment]
I'm having the same problem. Grails 3.6.2 plugin version 3.1.1
Any idea how I can fix it too?

`ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalAccessException occurred when processing request: [POST] /app/createUser
Class org.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public". Stacktrace follows:
java.lang.reflect.InvocationTargetException: null`

**Comment by shyamsundarv** [comment]
I'm having the same problem, unable to send message second time.
Grails version 2.3.7, Slack Plugin version 1.2.2.
Any idea how to resolve this issue?
ERROR org.grails.web.converters.marshaller.json.GenericJavaBeanMarshaller can not access a member of class org.springframework.beans.GenericTypeAwarePropertyDescriptor with modifiers "public".

**Comment by mathifonseca** [comment]
Hi @t2developer @shyamsundarv, sorry for the delay, I've been out of the Grails world for a while. Are you still having this problem? Maybe we can compare your dependency reports with @lesiki's and mine to find out who is causing the trouble.

**Comment by channy007** [comment]
i was error like this too.i'm using grails version 3.3.8. anyone please...
